### PR TITLE
JsonHelper

### PR DESCRIPTION
**Pull request by CaptKH**
Added functionality to JSON reader to extract int32, uint32, float, and GUID's

### CODE REVIEW

**Comment by raselneck** [comment]
Have you tested these changes? I don't know if `JsonExtractFloat`, `JsonExtractInt32`, or `JsonExtractUInt32` will work because I don't know if the JSON library specifically supports those `.get<T>` overloads. Even if they will work, you did not also add the macros for release configurations, so release builds will not work.

The `JsonExtractGuid(const std::string& name, Guid& out)` you added will **not** work. For what you're trying to do with that, just use `Guid::Parse`.

Also please remember to use spaces instead of tabs as your changes are all misaligned.

**Comment by CaptKH** [comment]
Wow didn't realize I missed so much, sorry Rich. I'll fix everything
tonight after I'm out of work. Thanks for the heads up man!

**Comment by CaptKH** [comment]
Also I forgot to mention that I did test pretty extensively to make sure
all the data was being stored properly, and everything was working on my
end.  I'll retest after implementing the changes to double check.

**Comment by raselneck** [comment]
Okay, cool. So the only changes you need to make are formatting and adding the defines for Release builds then, right?

If so, then after this is accepted I'll pull it into my fork then make a PR for my changes.

**Comment by CaptKH** [comment]
I redid it so that I didn't have to make any new JSON extract defines. Are
things still not formatted properly? I changed the setting in VS so that
tabbing is spaces instead of tabs, although I could've missed something.

**Comment by Honeybunch** [comment]
Just change all your existing tabs to spaces.
You can show whitespace with Ctrl-R - Ctrl-W
Change all existing whitespace by selecting the whole doc (Ctrl-A) and then going to Edit -> Advanced and selecting Untabify Lines

**Pull request closed without merging**
